### ISSUE TITLE
能否提供一份，键盘谱

### ISSUE THREAD

**Issue by frg666** [nwdxlgzs/GenshinImpactAutoMusic#1]
如题。能否提供一份，键盘谱。想尝试一下手搓，感觉你这个谱子比较还原，谢谢啦。

**Comment by nwdxlgzs** [comment]
app.py里头TapData内就是，但是不是谱子而是按键信息，谱子在B站视频简介下方提到了扒谱弹奏的原作者。

**Comment by frg666** [comment]
请问是哪位up？

**Comment by nwdxlgzs** [comment]
BV1Ju41127FL

**Comment by frg666** [comment]
> BV1Ju41127FL

感谢
